DROP TABLE IF EXISTS PRICES;

CREATE TABLE PRICES (
    BRAND_ID INT,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRICE_LIST INT,
    PRODUCT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PRIORITY INT,
    PRICE DECIMAL(10, 2),
    CURR VARCHAR(3)
);

/* BRAND_ID would be a foreign key to a different table we don't have */ 